fails:Integer.try_convert returns the argument if it's an Integer
fails:Integer.try_convert returns nil when the argument does not respond to #to_int
fails:Integer.try_convert sends #to_int to the argument and returns the result if it's nil
fails:Integer.try_convert sends #to_int to the argument and returns the result if it's an Integer
fails:Integer.try_convert sends #to_int to the argument and raises TypeError if it's not a kind of Integer
fails:Integer.try_convert does not rescue exceptions raised by #to_int
